# Generated by Django 4.1 on 2023-02-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=10)),
                ('gu', models.CharField(max_length=10)),
                ('dong', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=200)),
                ('context', models.TextField()),
            ],
        ),
    ]
