# Generated by Django 4.1 on 2023-02-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrec',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodrec',
            name='header_img',
            field=models.ImageField(blank=True, null=True, upload_to='blog/images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='foodrec',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
