# Generated by Django 4.1 on 2023-02-26 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_foodrec_created_at_alter_foodrec_header_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrec',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
