# Generated by Django 4.1 on 2023-02-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_foodrec_header_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrec',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
